{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llmtrace.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llmtrace.labels" . | nindent 4 }}
type: Opaque
stringData:
  LLMTRACE_CLICKHOUSE_URL: {{ .Values.secrets.clickhouseUrl | quote }}
  LLMTRACE_CLICKHOUSE_DATABASE: {{ .Values.secrets.clickhouseDatabase | quote }}
  LLMTRACE_POSTGRES_URL: {{ .Values.secrets.postgresUrl | quote }}
  LLMTRACE_REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
{{- end }}
